# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # upon creation of a file that matches the pattern *dev.yaml,
  # KMS set A is used
  # eGOV Internal ------------------------------------------------------------------------------------------------------------- #

  - path_regex: environments/azure-taraba-itn-uat-secrets.yaml$
    azure_keyvault: "https://taraba-itn-uat.vault.azure.net/keys/taraba-itn-uat-master-key/2c8d191a3bb546c2a365058db7686da3"

  - path_regex: environments/azure-taraba-itn-prod-secrets.yaml$
    azure_keyvault: "https://taraba-itn-prod.vault.azure.net/keys/taraba-itn-prod-master-key/c7d216c12b6a400293e57c45da7842dc"