{{- with index .Values "cluster-configs" "secrets" "project-factory" }}
{{- if index . "base-secret" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  base-secret: {{ index . "base-secret" | b64enc | quote }}
{{- end }}
{{- end }}
